// ==UserScript==
// @name         Better Google
// @namespace    google
// @version      0.1.16.11
// @author       aligo, adambh, tejaslodaya, drwonky, yut23
// @license      MIT
// @homepageURL   https://github.com/aligo/better-google
// @match        https://*.google.com/search?*
// @include      /^https?://(?:www|encrypted|ipv[46])\.google\.[^/]+/(?:$|[#?]|search|webhp)/
// @grant        none
// @run-at       document-start
// @downloadURL https://raw.githubusercontent.com/FiorenMas/Userscripts/release/release/Better20Google.user.js
// @updateURL https://raw.githubusercontent.com/FiorenMas/Userscripts/release/release/Better20Google.meta.js
// ==/UserScript==
(function(){"use strict";var y=function(t){var n=t.querySelectorAll(".TbwUpd, .HGLrXd");if(n.length>0){var e=[".yuRUbf > a",".yuRUbf > div > a",".yuRUbf > div > span > a"];for(const h of e){var r=t.querySelector(h);if(r)break}var o=r.nextSibling;if(o||(o=r.parentElement.nextSibling),!o)return;var i=document.createElement("div");i.className="btrAdd";for(var s=0;s<o.children.length;s++){var l=o.children[s];l.className.includes("TbwUpd")||l.className.includes("HGLrXd")||i.appendChild(l)}var c=document.createElement("div");c.className="btrG",c.appendChild(i),t.appendChild(c);var a=document.createElement("a");a.href=r.href,a.target="_blank",a.className="btrLink";var u=document.createElement("cite");u.innerText=r.href,u.className="iUh30 bc",a.appendChild(u);var b=t.clientWidth-i.offsetWidth-10;c.insertBefore(a,i),a.offsetWidth>b&&(a.style.width=b.toString()+"px");var f=t.querySelector(".csDOgf");f&&f.parentElement!==i&&i.appendChild(f),n.forEach(function(h){h.remove()});var g=r.querySelector("br:first-child");g&&g.remove()}},m=0,p=!1,v=function(){if(m!=document.querySelectorAll(".MjjYud .yuRUbf").length&&(document.querySelectorAll(".MjjYud .yuRUbf").forEach(y),m=document.querySelectorAll(".MjjYud .yuRUbf").length),!p){if(MutationObserver!=null){var t=document.getElementById("rcnt"),n=new MutationObserver(v);n.observe(t,{childList:!0,subtree:!0})}p=!0}},x=function(){var t="#006621",n=document.querySelector('meta[name="color-scheme"]');n!=null&&n.content.includes("dark")&&(t="#40965b");var e=document.createElement("style");e.setAttribute("media","screen"),e.appendChild(document.createTextNode("")),document.head.appendChild(e),e.sheet.insertRule(`:root { --btrG-link-color: ${t}; }`),e.sheet.insertRule(".btrG { display: flex; align-items: center; gap: 6px; word-break: normal; line-height: 18px; }"),e.sheet.insertRule(".btrG .btrAdd { display: inline-flex; align-items: center; flex: 0 0 auto; line-height: 18px; }"),e.sheet.insertRule(".btrG .btrAdd .csDOgf { display: inline-flex; align-items: center; height: 18px; margin: 0; padding: 0; }"),e.sheet.insertRule('.btrG .btrAdd .csDOgf > div, .btrG .btrAdd .csDOgf [role="button"] { display: inline-flex; align-items: center; height: 18px; margin: 0; padding: 0; }'),e.sheet.insertRule(".btrG .btrLink { display: block; flex: 0 1 auto; min-width: 0; line-height: 18px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; text-decoration: none !important; color: var(--btrG-link-color); }"),e.sheet.insertRule(".btrG .btrLink cite.iUh30 { color: var(--btrG-link-color); font-size: 16px; }"),e.sheet.insertRule(".yuRUbf h3.DKV0Md { margin-top: 0px; }")},d=function(t,n){var e=document.querySelector(t);e==null?window.requestAnimationFrame!=null?window.requestAnimationFrame(function(){d(t,n)}):document.addEventListener("readystatechange",function(r){document.readyState=="complete"&&n()}):n()};d("head",x),d("#rcnt",v)})();
