// ==UserScript==
// @name         Better Google
// @namespace    google
// @version      0.1.16.10
// @author       aligo, adambh, tejaslodaya, drwonky, yut23
// @license      MIT
// @homepageURL   https://github.com/aligo/better-google
// @match        https://*.google.com/search?*
// @include      /^https?://(?:www|encrypted|ipv[46])\.google\.[^/]+/(?:$|[#?]|search|webhp)/
// @grant        none
// @run-at       document-start
// @downloadURL https://raw.githubusercontent.com/FiorenMas/Userscripts/release/release/Better20Google.user.js
// @updateURL https://raw.githubusercontent.com/FiorenMas/Userscripts/release/release/Better20Google.meta.js
// ==/UserScript==
(function(){"use strict";var g=function(e){var r=e.querySelectorAll(".TbwUpd, .HGLrXd");if(r.length>0){var t=[".yuRUbf > a",".yuRUbf > div > a",".yuRUbf > div > span > a"];for(const f of t){var n=e.querySelector(f);if(n)break}var o=n.nextSibling;if(o||(o=n.parentElement.nextSibling),!o)return;var a=document.createElement("div");a.className="btrAdd";for(var s=0;s<o.children.length;s++){var l=o.children[s];l.className.includes("TbwUpd")||l.className.includes("HGLrXd")||a.appendChild(l)}var c=document.createElement("div");c.className="btrG",c.appendChild(a),e.appendChild(c);var i=document.createElement("a");i.href=n.href,i.target="_blank",i.className="btrLink";var u=document.createElement("cite");u.innerText=n.href,u.className="iUh30 bc",i.appendChild(u);var p=e.clientWidth-a.offsetWidth-10;c.insertBefore(i,a),i.offsetWidth>p&&(i.style.width=p.toString()+"px");var b=e.querySelectorAll(".csDOgf");b.length>0&&c.appendChild(b[0]),r.forEach(function(f){f.remove()});var y=n.querySelector("br:first-child");y&&y.remove()}},h=0,m=!1,v=function(){if(h!=document.querySelectorAll(".MjjYud .yuRUbf").length&&(document.querySelectorAll(".MjjYud .yuRUbf").forEach(g),h=document.querySelectorAll(".MjjYud .yuRUbf").length),!m){if(MutationObserver!=null){var e=document.getElementById("rcnt"),r=new MutationObserver(v);r.observe(e,{childList:!0,subtree:!0})}m=!0}},w=function(){var e="#006621",r=document.querySelector('meta[name="color-scheme"]');r!=null&&r.content.includes("dark")&&(e="#40965b");var t=document.createElement("style");t.setAttribute("media","screen"),t.appendChild(document.createTextNode("")),document.head.appendChild(t),t.sheet.insertRule(`:root { --btrG-link-color: ${e}; }`),t.sheet.insertRule(".btrG { word-break: normal; line-height: 18px; }"),t.sheet.insertRule(".btrG .btrAdd { display: inline-block; vertical-align: top; line-height: 0; }"),t.sheet.insertRule(".btrG .btrLink { display: inline-block; vertical-align: top; line-height: 18px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; text-decoration: none !important; color: var(--btrG-link-color); }"),t.sheet.insertRule(".btrG .btrLink cite.iUh30 { color: var(--btrG-link-color); font-size: 16px; }"),t.sheet.insertRule(".yuRUbf h3.DKV0Md { margin-top: 0px; }")},d=function(e,r){var t=document.querySelector(e);t==null?window.requestAnimationFrame!=null?window.requestAnimationFrame(function(){d(e,r)}):document.addEventListener("readystatechange",function(n){document.readyState=="complete"&&r()}):r()};d("head",w),d("#rcnt",v)})();
