// ==UserScript==
// @name               Google & baidu Switcher (ALL in One)
// @name:en            Search Engine Assistant
// @version            2026.09.05.1
// @author             F9y4ng
// @icon               data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAz1BMVEUAAACFhYXw8PHs7Ozf39/z8/MWFhbr6+vu7u7n5+fz8/MAAADBwcHu7u6IiIgqKioQEBDh4eHV1dXy8vLT09Ovr6/W1tZeXl6tra1PT08DAwPw8PDw8PCZmZlwv//y8vLZ7v9kbZxQUYNgktBbg75uu/xttvZqrOrPzthlouBrndZtj8hve75gYY68vM2Qjq1PSnx7rOBjmtewrsGcmbRZdKuGhaat0/bn5+pFP3TU7P+ax/CNvOpdi8hziL5saJK43Pve3eNleq17dpu80O9iKsm6AAAAHnRSTlMAfPrtCC0m4n9uFQiypWZdGdrNubKmnXduWEM8IZf1WLSqAAABZUlEQVQ4y9WQ2XaCMBRFaUCt1nnooDZXIpNMggxCnbX//00NAbR0YV/61P2WdXZO7g33L6lMKsL9dNpCAIBakzt5HYG9DJcegufyHDTL2huG6NgwLHsdaY6OE1TiwevPWKgMEKF5ajinWrcQN5LpPBHnSCG0C+18Mp01vwoqgdH3+7XoYBnGWcFYVlUlMWLo1RtX4REuZ8xY6NuNu1KwHEcIUD0XahrJ8u3HbDY7rhQ1JvFBy75DeAQvYLni0pyyXmEZY53YbFlhANolFRbrWYoup8tG/adkAJ/s1VQ4ZoKrsHPgoSrH8Rqhx7IGLC3hjWuAL+EMxU3z9TwTfCpMc+G2xefeWDGDaPyYPSHfDH2zceemyYxAhGY1GXJJpHnOTpJ2UkCNnUSsiO/QLYQe2KFYwHJMUyQ28C9d9lFNBEVop3kIodmpcinV9kOBPviOdaqNaX85whCA9d+nPXqn/b+S1/+dL1CJQlhxaUFqAAAAAElFTkSuQmCC
// @namespace          https://github.com/F9y4ng/GreasyFork-Scripts/
// @homepage           https://f9y4ng.github.io/GreasyFork-Scripts/
// @homepageURL        https://f9y4ng.github.io/GreasyFork-Scripts/
// @supportURL         https://github.com/F9y4ng/GreasyFork-Scripts/issues
// @require            https://f9y4ng.github.io/GreasyFork-Scripts/lib/parallelGMxhr.js#sha256-qo7Imc1jg2AryApKESDzER/AO92l55w1dH7+xsxrx2I=
// @match              *://www.baidu.com/*
// @match              *://ipv6.baidu.com/*
// @match              *://image.baidu.com/search*
// @match              *://kaifa.baidu.com/searchPage*
// @match              *://*.bing.com/*search?*
// @match              *://*.bing.com/videos/riverview/relatedvideo?*
// @match              *://duckduckgo.com/*
// @match              *://*.sogou.com/*
// @match              *://www.qwant.com/?*
// @match              *://www.so.com/s*
// @match              *://image.so.com/*
// @match              *://so.toutiao.com/search*
// @match              *://yandex.com/*search*
// @match              *://yandex.ru/*search*
// @match              *://www.ecosia.org/*
// @match              *://*.search.yahoo.com/search*
// @match              *://www.info.com/serp?*
// @match              *://www.startpage.com/*
// @match              *://search.brave.com/*
// @match              *://yep.com/*
// @match              *://www.mojeek.com/search*
// @match              *://au.priv.au/search*
// @match              *://*.google.ad/search?*
// @match              *://*.google.ae/search?*
// @match              *://*.google.al/search?*
// @match              *://*.google.am/search?*
// @match              *://*.google.as/search?*
// @match              *://*.google.at/search?*
// @match              *://*.google.az/search?*
// @match              *://*.google.ba/search?*
// @match              *://*.google.be/search?*
// @match              *://*.google.bf/search?*
// @match              *://*.google.bg/search?*
// @match              *://*.google.bi/search?*
// @match              *://*.google.bj/search?*
// @match              *://*.google.bs/search?*
// @match              *://*.google.bt/search?*
// @match              *://*.google.by/search?*
// @match              *://*.google.ca/search?*
// @match              *://*.google.cat/search?*
// @match              *://*.google.cd/search?*
// @match              *://*.google.cf/search?*
// @match              *://*.google.cg/search?*
// @match              *://*.google.ch/search?*
// @match              *://*.google.ci/search?*
// @match              *://*.google.cl/search?*
// @match              *://*.google.cm/search?*
// @match              *://*.google.cn/search?*
// @match              *://*.google.co.ao/search?*
// @match              *://*.google.co.bw/search?*
// @match              *://*.google.co.ck/search?*
// @match              *://*.google.co.cr/search?*
// @match              *://*.google.co.id/search?*
// @match              *://*.google.co.il/search?*
// @match              *://*.google.co.in/search?*
// @match              *://*.google.co.jp/search?*
// @match              *://*.google.co.ke/search?*
// @match              *://*.google.co.kr/search?*
// @match              *://*.google.co.ls/search?*
// @match              *://*.google.co.ma/search?*
// @match              *://*.google.co.mz/search?*
// @match              *://*.google.co.nz/search?*
// @match              *://*.google.co.th/search?*
// @match              *://*.google.co.tz/search?*
// @match              *://*.google.co.ug/search?*
// @match              *://*.google.co.uk/search?*
// @match              *://*.google.co.uz/search?*
// @match              *://*.google.co.ve/search?*
// @match              *://*.google.co.vi/search?*
// @match              *://*.google.co.za/search?*
// @match              *://*.google.co.zm/search?*
// @match              *://*.google.co.zw/search?*
// @match              *://*.google.com/search?*
// @match              *://*.google.com.af/search?*
// @match              *://*.google.com.ag/search?*
// @match              *://*.google.com.ar/search?*
// @match              *://*.google.com.au/search?*
// @match              *://*.google.com.bd/search?*
// @match              *://*.google.com.bh/search?*
// @match              *://*.google.com.bn/search?*
// @match              *://*.google.com.bo/search?*
// @match              *://*.google.com.br/search?*
// @match              *://*.google.com.bz/search?*
// @match              *://*.google.com.co/search?*
// @match              *://*.google.com.cu/search?*
// @match              *://*.google.com.cy/search?*
// @match              *://*.google.com.do/search?*
// @match              *://*.google.com.ec/search?*
// @match              *://*.google.com.eg/search?*
// @match              *://*.google.com.et/search?*
// @match              *://*.google.com.fj/search?*
// @match              *://*.google.com.gh/search?*
// @match              *://*.google.com.gi/search?*
// @match              *://*.google.com.gt/search?*
// @match              *://*.google.com.hk/search?*
// @match              *://*.google.com.jm/search?*
// @match              *://*.google.com.kh/search?*
// @match              *://*.google.com.kw/search?*
// @match              *://*.google.com.lb/search?*
// @match              *://*.google.com.ly/search?*
// @match              *://*.google.com.mm/search?*
// @match              *://*.google.com.mt/search?*
// @match              *://*.google.com.mx/search?*
// @match              *://*.google.com.my/search?*
// @match              *://*.google.com.na/search?*
// @match              *://*.google.com.ng/search?*
// @match              *://*.google.com.ni/search?*
// @match              *://*.google.com.np/search?*
// @match              *://*.google.com.om/search?*
// @match              *://*.google.com.pa/search?*
// @match              *://*.google.com.pe/search?*
// @match              *://*.google.com.pg/search?*
// @match              *://*.google.com.ph/search?*
// @match              *://*.google.com.pk/search?*
// @match              *://*.google.com.pr/search?*
// @match              *://*.google.com.py/search?*
// @match              *://*.google.com.qa/search?*
// @match              *://*.google.com.sa/search?*
// @match              *://*.google.com.sb/search?*
// @match              *://*.google.com.sg/search?*
// @match              *://*.google.com.sl/search?*
// @match              *://*.google.com.sv/search?*
// @match              *://*.google.com.tj/search?*
// @match              *://*.google.com.tr/search?*
// @match              *://*.google.com.tw/search?*
// @match              *://*.google.com.ua/search?*
// @match              *://*.google.com.uy/search?*
// @match              *://*.google.com.vc/search?*
// @match              *://*.google.com.vn/search?*
// @match              *://*.google.cv/search?*
// @match              *://*.google.cz/search?*
// @match              *://*.google.de/search?*
// @match              *://*.google.dj/search?*
// @match              *://*.google.dk/search?*
// @match              *://*.google.dm/search?*
// @match              *://*.google.dz/search?*
// @match              *://*.google.ee/search?*
// @match              *://*.google.es/search?*
// @match              *://*.google.fi/search?*
// @match              *://*.google.fm/search?*
// @match              *://*.google.fr/search?*
// @match              *://*.google.ga/search?*
// @match              *://*.google.ge/search?*
// @match              *://*.google.gg/search?*
// @match              *://*.google.gl/search?*
// @match              *://*.google.gm/search?*
// @match              *://*.google.gr/search?*
// @match              *://*.google.gy/search?*
// @match              *://*.google.hn/search?*
// @match              *://*.google.hr/search?*
// @match              *://*.google.ht/search?*
// @match              *://*.google.hu/search?*
// @match              *://*.google.ie/search?*
// @match              *://*.google.im/search?*
// @match              *://*.google.iq/search?*
// @match              *://*.google.is/search?*
// @match              *://*.google.it/search?*
// @match              *://*.google.je/search?*
// @match              *://*.google.jo/search?*
// @match              *://*.google.kg/search?*
// @match              *://*.google.ki/search?*
// @match              *://*.google.kz/search?*
// @match              *://*.google.la/search?*
// @match              *://*.google.li/search?*
// @match              *://*.google.lk/search?*
// @match              *://*.google.lt/search?*
// @match              *://*.google.lu/search?*
// @match              *://*.google.lv/search?*
// @match              *://*.google.md/search?*
// @match              *://*.google.me/search?*
// @match              *://*.google.mg/search?*
// @match              *://*.google.mk/search?*
// @match              *://*.google.ml/search?*
// @match              *://*.google.mn/search?*
// @match              *://*.google.mu/search?*
// @match              *://*.google.mv/search?*
// @match              *://*.google.mw/search?*
// @match              *://*.google.ne/search?*
// @match              *://*.google.nl/search?*
// @match              *://*.google.no/search?*
// @match              *://*.google.nr/search?*
// @match              *://*.google.nu/search?*
// @match              *://*.google.pl/search?*
// @match              *://*.google.pn/search?*
// @match              *://*.google.ps/search?*
// @match              *://*.google.pt/search?*
// @match              *://*.google.ro/search?*
// @match              *://*.google.rs/search?*
// @match              *://*.google.ru/search?*
// @match              *://*.google.rw/search?*
// @match              *://*.google.sc/search?*
// @match              *://*.google.se/search?*
// @match              *://*.google.sh/search?*
// @match              *://*.google.si/search?*
// @match              *://*.google.sk/search?*
// @match              *://*.google.sm/search?*
// @match              *://*.google.sn/search?*
// @match              *://*.google.so/search?*
// @match              *://*.google.sr/search?*
// @match              *://*.google.st/search?*
// @match              *://*.google.td/search?*
// @match              *://*.google.tg/search?*
// @match              *://*.google.tl/search?*
// @match              *://*.google.tm/search?*
// @match              *://*.google.tn/search?*
// @match              *://*.google.to/search?*
// @match              *://*.google.tt/search?*
// @match              *://*.google.vu/search?*
// @match              *://*.google.ws/search?*
// @exclude            *://www.baidu.com/link*
// @exclude            *://www.sogou.com/link*
// @exclude            *://so.toutiao.com/search/jump*
// @connect            self
// @connect            greasyfork.org
// @connect            openuserjs.org
// @connect            githubusercontent.com
// @connect            favicon.yandex.net
// @grant              GM_getValue
// @grant              GM.getValue
// @grant              GM_setValue
// @grant              GM.setValue
// @grant              GM_listValues
// @grant              GM.listValues
// @grant              GM_deleteValue
// @grant              GM.deleteValue
// @grant              GM_openInTab
// @grant              GM.openInTab
// @grant              GM_addElement
// @grant              GM_registerMenuCommand
// @grant              GM.registerMenuCommand
// @grant              GM_xmlhttpRequest
// @grant              GM.xmlHttpRequest
// @grant              unsafeWindow
// @note               {"CN":"移除 You.com 搜索，新增 info.com 搜索。","EN":"Removed You.com, Added info.com."}
// @note               {"CN":"优化 Google 搜索结果连接重定向的问题。","EN":"Optimized Google search result redirection issues."}
// @note               {"CN":"优化 duckduckgo 默认打开新窗口的设置。","EN":"Optimized duckduckgo for opening new windows."}
// @note               {"CN":"修复关键词屏蔽功能偶发失效的问题。","EN":"Fixed sporadic failure issue of the keyword blocking."}
// @note               {"CN":"修复 Google 跳转按钮未插入的问题。","EN":"Fixed Google the jump button was not inserted issue."}
// @note               {"CN":"修正一些已知问题，优化代码，优化样式。","EN":"Fixed some known issues, optimized code & style."}
// @compatible         Edge version≥88 (Compatible Tampermonkey, Violentmonkey)
// @compatible         Chrome version≥88 (Compatible Tampermonkey, Violentmonkey)
// @compatible         Firefox version≥78 (Compatible Greasemonkey, Tampermonkey, Violentmonkey)
// @compatible         Opera version≥75 (Compatible Tampermonkey, Violentmonkey)
// @compatible         Safari version≥14 (Compatible Tampermonkey, Userscripts)
// @license            GPL-3.0-only
// @copyright          2015-2026, F9y4ng
// @run-at             document-start
// @downloadURL https://raw.githubusercontent.com/FiorenMas/Userscripts/release/release/E4BC98E99B85E79A84E6909CE7B4A2E5BC95E6938EE58AA9E6898B.user.js
// @updateURL https://raw.githubusercontent.com/FiorenMas/Userscripts/release/release/E4BC98E99B85E79A84E6909CE7B4A2E5BC95E6938EE58AA9E6898B.meta.js
// ==/UserScript==
