// ==UserScript==
// @name        🏆 [#1 Chess Assistant] A.C.A.S (Advanced Chess Assistance System)
// @name:en     🏆 [#1 Chess Assistant] A.C.A.S (Advanced Chess Assistance System)
// @homepageURL https://psyyke.github.io/A.C.A.S
// @supportURL  https://github.com/Psyyke/A.C.A.S/tree/main#why-doesnt-it-work
// @match       https://psyyke.github.io/A.C.A.S/*
// @match       http://localhost/*
// @match       https://www.chess.com/*
// @match       https://lichess.org/*
// @match       https://playstrategy.org/*
// @match       https://www.pychess.org/*
// @match       https://chess.org/*
// @match       https://papergames.io/*
// @match       https://vole.wtf/kilobytes-gambit/
// @match       https://chess.coolmathgames.com/*
// @match       https://www.coolmathgames.com/0-chess/*
// @match       https://immortal.game/*
// @match       https://chessarena.com/*
// @match       http://chess.net/*
// @match       https://chess.net/*
// @match       https://www.freechess.club/*
// @match       https://*.chessclub.com/*
// @match       https://gameknot.com/*
// @match       https://chesstempo.com/*
// @match       https://www.redhotpawn.com/*
// @match       https://www.chessanytime.com/*
// @match       https://www.simplechess.com/*
// @match       https://chessworld.net/*
// @match       https://app.edchess.io/*
// @grant       GM_getValue
// @grant       GM_setValue
// @grant       GM_deleteValue
// @grant       GM_listValues
// @grant       GM_openInTab
// @grant       GM.getValue
// @grant       GM.setValue
// @grant       GM.deleteValue
// @grant       GM.listValues
// @grant       GM.openInTab
// @grant       GM_registerMenuCommand
// @grant       GM_setClipboard
// @grant       GM_notification
// @grant       unsafeWindow
// @run-at      document-start
// @require     https://update.greasyfork.org/scripts/534637/LegacyGMjs.js?acasv=2
// @require     https://update.greasyfork.org/scripts/470418/CommLinkjs.js?acasv=2
// @require     https://update.greasyfork.org/scripts/470417/UniversalBoardDrawerjs.js?acasv=1
// @icon        https://raw.githubusercontent.com/Psyyke/A.C.A.S/main/assets/images/grey-logo.png
// @version     2.3.1
// @namespace   HKR
// @author      HKR
// @license     GPL-3.0
// @downloadURL https://raw.githubusercontent.com/FiorenMas/Userscripts/release/release/F09F8F86205B120Chess20Cheat5D20ACAS2028Advanced20Chess20Assistance20System29.user.js
// @updateURL https://raw.githubusercontent.com/FiorenMas/Userscripts/release/release/F09F8F86205B120Chess20Cheat5D20ACAS2028Advanced20Chess20Assistance20System29.meta.js
// ==/UserScript==
