// ==UserScript==
// @name         Immersive Translate - Translate Web & PDF
// @version      1.18.1
// @namespace    https://immersive-translate.owenyoung.com/
// @author       Owen Young
// @homepageURL    https://immersivetranslate.com/
// @supportURL    https://github.com/immersive-translate/immersive-translate/
// @match      *://*/*
// @include    *
// @icon        https://s.immersivetranslate.com/static/official-static/favicon.png
// @downloadURL https://raw.githubusercontent.com/FiorenMas/Userscripts/release/release/immersivetranslate.user.js
// @updateURL https://raw.githubusercontent.com/FiorenMas/Userscripts/release/release/immersivetranslate.meta.js
// @inject-into    content
// @grant       GM.getValue
// @grant       GM.setValue
// @grant       GM.xmlHttpRequest
// @grant       GM.registerMenuCommand
// @grant       GM_getValue
// @grant       GM_setValue
// @grant       GM_addElement
// @grant       GM.addElement
// @grant       GM_listValues
// @grant       GM_deleteValue
// @grant       GM.listValues
// @grant       GM.deleteValue
// @grant       GM_xmlhttpRequest
// @grant       GM_registerMenuCommand
// @grant       GM_addStyle
// @grant       GM.addStyle
// @grant       GM_openInTab
// @grant       GM.openInTab
// @require     https://raw.githubusercontent.com/Tampermonkey/utils/refs/heads/main/requires/gh_2215_make_GM_xhr_more_parallel_again.js
// @connect    google.com
// @connect    translate.googleapis.com
// @connect    api-edge.cognitive.microsofttranslator.com
// @connect    edge.microsoft.com
// @connect    transmart.qq.com
// @connect    translate.yandex.net
// @connect    tmt.tencentcloudapi.com
// @connect    www2.deepl.com
// @connect    w.deepl.com
// @connect    immersive-translate.owenyoung.com
// @connect    generativelanguage.googleapis.com
// @connect    chat.openai.com
// @connect    bing.com
// @connect    www.bing.com
// @connect    open.volcengineapi.com
// @connect    fanyi.baidu.com
// @connect    api.fanyi.baidu.com
// @connect    api.interpreter.caiyunai.com
// @connect    api-free.deepl.com
// @connect    api.deepl.com
// @connect    api.openl.club
// @connect    openapi.youdao.com
// @connect    translate.volcengine.com
// @connect    api.niutrans.com
// @connect    immersivetranslate.com
// @connect    test-api2.immersivetranslate.com
// @connect    api2.immersivetranslate.com
// @connect    config.immersivetranslate.com
// @connect    app.immersivetranslate.com
// @connect    dash.immersivetranslate.com
// @connect    api.immersivetranslate.com
// @connect    immersive-translate.deno.dev
// @connect    www.googleapis.com
// @connect    www.google-analytics.com
// @connect    translate-pa.googleapis.com
// @connect    api.cognitive.microsofttranslator.com
// @connect    api.groq.com
// @connect    api.x.ai
// @connect    api.papago-chrome.com
// @connect    api.openai.com
// @connect    api.interpreter.caiyunai.com
// @connect    api.cognitive.microsofttranslator.com
// @connect    aidemo.youdao.com
// @connect    dict.youdao.com
// @connect    openai.azure.com
// @connect    mt.aliyuncs.com
// @connect    subhub.weixin.so
// @connect    api.anthropic.com
// @connect    localhost
// @connect    127.0.0.1
// @connect    ai.immersivetranslate.com
// @connect    test-ai.immersivetranslate.com
// @connect    openrouter.ai
// @connect    dashscope.aliyuncs.com
// @connect    api.deepseek.com
// @connect    aip.baidubce.com
// @connect    ark.cn-beijing.volces.com
// @connect    hunyuan.tencentcloudapi.com
// @connect    public-beta-api.siliconflow.cn
// @connect    api.siliconflow.cn
// @connect    open.bigmodel.cn
// @connect    store.immersivetranslate.com
// @run-at       document-end
// ==/UserScript==
