// ==UserScript==
// @name        Lazyloadfier Userscript
// @namespace   Lazyloadfier Userscript - Violentmonkey Scripts
// @match       *://*/*
// @grant       none
// @version     1.0
// @run-at      document-start
// @author      -
// @description 9/8/2023, 1:42:06 AM
// @downloadURL https://raw.githubusercontent.com/FiorenMas/Userscripts/release/release/Lazyloadfier20Userscript.user.js
// @updateURL https://raw.githubusercontent.com/FiorenMas/Userscripts/release/release/Lazyloadfier20Userscript.meta.js
// ==/UserScript==
const SRC_ATTRIBUTE_NAME="src",SRCSET_ATTRIBUTE_NAME="srcset",POSTER_ATTRIBUTE_NAME="poster",LOADING_ATTRIBUTE_NAME="loading",LAZY_LOADING_ATTRIBUTE_VALUE="lazy",IMG_TAG_NAME="IMG",VIDEO_TAG_NAME="VIDEO",AUDIO_TAG_NAME="AUDIO",SOURCE_TAG_NAME="SOURCE",IFRAME_TAG_NAME="IFRAME",FRAME_TAG_NAME="FRAME",EMBED_TAG_NAME="EMBED",TAG_NAMES_WITH_SRC_ATTRIBUTE=new Set(["IMG","VIDEO","AUDIO","SOURCE","IFRAME","FRAME","EMBED"]),TAG_NAMES_WITH_SRCSET_ATTRIBUTE=new Set(["IMG","SOURCE"]),TAG_NAMES_WITH_POSTER_ATTRIBUTE=new Set(["VIDEO"]),OBSERVED_TAGS_SELECTOR=Array.from(TAG_NAMES_WITH_SRC_ATTRIBUTE).join(","),UNSENT_READY_STATE=0,DOM_CONTENT_LOADED_EVENT="DOMContentLoaded",EMPTY_DEFAULT_DATA_URI="data:,",EMPTY_IMAGE_DATA_URI="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",EMPTY_TEXT_DATA_URI="data:text/plain,",EMPTY_DATA_URI=new Map([["VIDEO","data:,"],["AUDIO","data:,"],["SOURCE",EMPTY_IMAGE_DATA_URI],["IMG",EMPTY_IMAGE_DATA_URI],["IFRAME","data:text/plain,"],["FRAME","data:text/plain,"],["EMBED","data:text/plain,"]]),MUTATION_OBSERVER_OPTIONS={childList:!0,subtree:!0},MINIMUM_INTERSECTION_RATIO=0,MUTATION_OBSERVER_TIMEOUT=2500;function observeDocumentMutations(){const e={},t=new MutationObserver((e=>mutationObserverCallback(e,A)));function A(){deferDisconnectObserver(t,e)}t.observe(document,MUTATION_OBSERVER_OPTIONS),addEventListener("DOMContentLoaded",A)}function deferDisconnectObserver(e,t){t.id&&clearTimeout(t.id),t.id=setTimeout((()=>e.disconnect()),2500)}function mutationObserverCallback(e,t){const A=getObservedNodes(e);A.length&&(A.forEach(observeNodeIntersection),t(A))}function getObservedNodes(e){const t=[];return e.forEach((e=>{const A=new Set(e.addedNodes);A.forEach((e=>{e.querySelectorAll&&e.querySelectorAll(OBSERVED_TAGS_SELECTOR).forEach((e=>A.add(e)))})),t.splice(0,0,...Array.from(A).filter(matchObservedNode))})),t}function matchObservedNode(e){return TAG_NAMES_WITH_SRC_ATTRIBUTE.has(e.tagName)&&nodeIsHidden(e)&&"lazy"!=e.loading}function nodeIsHidden(e){const t=e.getBoundingClientRect();return t.bottom<0||t.top>innerHeight||t.left<0||t.right>innerWidth}function observeNodeIntersection(e){const t=resetSource(e,"src"),A=resetSource(e,"srcset"),E=resetSource(e,"poster");new IntersectionObserver(((T,n)=>intersectionObserverCallback(T,e,n,{src:t,srcset:A,poster:E}))).observe("SOURCE"==e.tagName?e.parentElement:e)}function intersectionObserverCallback(e,t,A,E){const T=e[0];T&&T.intersectionRatio>0&&(replaceSource(t,E),A.disconnect())}function replaceSource(e,t){setSource(e,"src",t.src),TAG_NAMES_WITH_SRCSET_ATTRIBUTE.has(e.tagName)&&setSource(e,"srcset",t.srcset),TAG_NAMES_WITH_POSTER_ATTRIBUTE.has(e.tagName)&&setSource(e,"poster",t.poster)}function resetSource(e,t){const A=e[t];if(A)return e[t]=EMPTY_DATA_URI.get(e.tagName),A}function setSource(e,t,A){e[t]==EMPTY_DATA_URI.get(e.tagName)&&(A?e[t]=A:(e.removeAttribute(t),0===e.readyState&&e.load()))}observeDocumentMutations();