// ==UserScript==
// @name         Pixeldrain Download Bypass
// @namespace    http://tampermonkey.net/
// @version      1.6.3
// @author       MegaLime0, honey, Nurarihyon
// @match        https://pixeldrain.com/*
// @match        https://cdn.pd8.workers.dev/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=pixeldrain.com
// @grant        GM_openInTab
// @downloadURL https://raw.githubusercontent.com/FiorenMas/Userscripts/release/release/Pixeldrain20Download20Bypass.user.js
// @updateURL https://raw.githubusercontent.com/FiorenMas/Userscripts/release/release/Pixeldrain20Download20Bypass.meta.js
// ==/UserScript==
(function(){"use strict";const f="https://pd.cybar.xyz/",b=/\/api\/file\/(\w+)\//;function m(t){const n=window.location.href;if(t=="file"){const i=n.replace("https://pixeldrain.com/u/","");return f+i}if(t=="gallery"){const i=document.querySelectorAll("a.file"),o=[],c=[];return i.forEach(p=>{const a=p.querySelector("div").style.backgroundImage.match(b);if(a&&a.length>1){const s=f+a[1];o.push(s),c.push(p.textContent)}}),{bypassUrlList:o,bypassUrlNames:c}}}function E(){const t=window.location.href;if(t.includes("https://pixeldrain.com/u/")){const n=m("file");h(n)}t.includes("https://pixeldrain.com/l/")&&m("gallery").bypassUrlList.forEach(i=>{h(i)})}function h(t){const n=document.createElement("a");n.href=t,n.click()}function g(){const t=document.getElementById("popupBox"),n=document.createElement("span");n.innerHTML="&times;",n.style.position="absolute",n.style.top="1px",n.style.right="7px",n.style.cursor="pointer",n.onclick=function(){t.style.display="none"},t.innerHTML="",t.appendChild(n);const i=window.location.href;if(i.includes("https://pixeldrain.com/u/")){const o=m("file"),c=document.createElement("a");c.href=o,c.textContent=o,t.appendChild(c)}if(i.includes("https://pixeldrain.com/l/")){let o=m("gallery"),c=o.bypassUrlList,p=o.bypassUrlNames;const e=document.createElement("div");e.style.maxHeight="calc(100% - 40px)",e.style.overflowY="auto",e.style.paddingBottom="10px",c.forEach(l=>{const d=document.createElement("a");d.href=l,d.textContent=l,d.style.display="block",e.appendChild(d)}),t.appendChild(e),t.style.display="flex",t.style.flexDirection="column",t.style.alignItems="center",t.style.justifyContent="center";const r=document.createElement("div");r.style.display="flex",r.style.justifyContent="center",r.style.marginTop="10px";const a=document.createElement("button");a.textContent="\u{1F517} Copy URL",a.style.marginRight="5px",a.addEventListener("click",function(){const l=c.join(`
`);navigator.clipboard.writeText(l).then(function(){a.textContent="\u2714\uFE0F Copied",setTimeout(function(){a.textContent="\u{1F517} Copy URL"},2500)},function(d){console.error("Failed to copy URLs: ",d)})}),r.appendChild(a);const s=document.createElement("button");s.textContent="\u{1F4C4} Save as Text File",s.style.marginLeft="5px",s.addEventListener("click",function(){const l=document.getElementById("popupBox").querySelectorAll("a");if(l.length>0){const y=window.location.href.match(/\/l\/([^/#?]+)/);if(y&&y.length>1){const U=y[1]+".txt";let x="";l.forEach(w=>{x+=w.href+`
`});const k=new Blob([x.trim()],{type:"text/plain"}),C=URL.createObjectURL(k),u=document.createElement("a");u.href=C,u.download=U,document.body.appendChild(u),u.click(),document.body.removeChild(u),URL.revokeObjectURL(C)}else console.error("Failed to extract file identifier from URL.")}else console.error("Popup content not found.")}),r.appendChild(s),t.appendChild(r)}t.style.display="block"}if(window.location.href.includes("pixeldrain.com")){let a=function(s){const l=s.getBoundingClientRect();s.style.top=`calc(50% - ${l.height/2}px)`,s.style.left=`calc(50% - ${l.width/2}px)`};const t=document.createElement("button"),n=document.createElement("a");n.className="icon",n.textContent="download",n.style.color="#d7dde8";const i=document.createElement("span");i.textContent="Download Bypass",t.appendChild(n),t.appendChild(i);const o=document.createElement("button"),c=document.createElement("i");c.className="icon",c.textContent="link";const p=document.createElement("span");p.textContent="Show Bypass Links",o.appendChild(c),o.appendChild(p);const e=document.createElement("div");e.style.zIndex=20,e.style.whiteSpace="pre-line",e.id="popupBox",e.style.display="none",e.style.position="fixed",e.style.top="50%",e.style.left="50%",e.style.transform="translate(-50%, -50%)",e.style.padding="20px",e.style.background="#2f3541",e.style.border="2px solid #a4be8c",e.style.color="#d7dde8",e.style.borderRadius="10px",e.style.width="30%",e.style.height="auto",e.style.maxWidth="600px",t.addEventListener("click",E),o.addEventListener("click",g),document.querySelectorAll("div.label").forEach(s=>{if(s.textContent.trim()==="Size"){const l=s.nextElementSibling;l&&(l.insertAdjacentElement("afterend",o),l.insertAdjacentElement("afterend",t))}}),document.body.appendChild(e)}})();
